### ISSUE TITLE
Script for transforming terrain textures from dimetric to flat

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage-modding#5]
Some people might want to design their terrain textures in dimetric (isometric) projection because that's how the textures will appear in the game. I suggest we write a script that inverses the transformation done in the render to generate the "flat" texture from a dimetric version. The transformation is pretty [straight forward](https://gamedev.stackexchange.com/a/16757) with a transformation matrix:

```
|  1   -1    0 |
|  0.5  0.5  n |
|  0    0    0 |
```

**Comment by TheJJ** [comment]
Indeed. This has to be done anyway in order to convert the AoE:TC terrain graphics to the "flat" texture we will then render.

**Comment by heinezen** [comment]
Solved by #6
