### ISSUE TITLE
`terrain_transform.py` transform and then inverse_transform does not result in the original image

### ISSUE THREAD

**Issue by e00E** [SFTtech/openage-modding#9]
Original:
![original](https://user-images.githubusercontent.com/1462179/38459453-1d979f32-3aaa-11e8-8bf1-67bffeddcf25.png)
Transformed:
![transformed](https://user-images.githubusercontent.com/1462179/38459454-1dc834d0-3aaa-11e8-91ad-8bf14d8a9f7f.png)
Inverse Transformed:
![inverse transformed](https://user-images.githubusercontent.com/1462179/38459452-1d7846b4-3aaa-11e8-81ba-b63f58d7303c.png)

If you zoom in you will see some pixels in the top right and bottom left corners are wrong.

**Comment by heinezen** [comment]
Yes, this unfortunately happens in some cases when applying the AoE2 rules on a texture. Take a 5x5 texture for example.

```
#####
#####
#####
#####
#####
```
```
    #
  #####
#########
  #####
    #
```

The result will be something like this. As you notice, it has fewer pixels than the original image. Or in other words, some pixels from the original will get projected to the same target pixel. As far as i know, this is already accounted for in HD edition textures (although I didn't test all of them) and it only affects 4-7 pixels per image.

**Comment by TheJJ** [comment]
Do you have any suggestion on how to fix this? In practice it should not be important because we will hopefully only go from diamond -> square.

**Comment by heinezen** [comment]
> Do you have any suggestion on how to fix this?

Removing the flooring and ceiling of coordinates during the transformation is one solution. Although this can destroy the 2:1 ratio that's required for dimetric. On larger images the error is so marginal that it has no visible effect on the texture.

> In practice it should not be important because we will hopefully only go from diamond -> square.

Well, doesn't the renderer do square -> diamond when displaying the texture? Surely, this problem would be something we'd have to think about then. Maybe this is more suited for you, @Vtec234 , since I'm far from being an expert on graphics programming.

**Comment by TheJJ** [comment]
The GPU will do the transformation with funny texture effects anyway in ways we can barely influence (except texture filtering, the shader code, ...) but the transformation is done in the vertex shader already.

**Comment by heinezen** [comment]
Oh, in that case we should have nothing to worry about :)

**Comment by Vtec234** [comment]
If I remember correctly, we decided to have the renderer only take square textures as input. Then, when it does render them it will apply the square->diamond transformation. This means that for old-style texture files (diamonds) the asset conversion should turn them into squares.

**Comment by TheJJ** [comment]
The update to the script solves the rotation direction, but the inverse transform problem may still persist. As @Vtec234 said, we just take the square texture in the renderer, which then applies the perspective view. For the relevant result (to display the terrain) that's all we can do, and what the HD-edition does as well.
